name: Build

on:
  push:
    branches:
      - "dev"

  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: frontend
    - run: npm run build --if-present
      working-directory: frontend

  build-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: server
    - run: npm run build --if-present
      working-directory: server